### ISSUE TITLE
prettier + eslint + recase each package

### ISSUE THREAD

**Issue by hamilton** [graph-paper-org/graph-paper#33]
We will need to manually handle eslint errors in the packages that were set up before linting before we can add the lint check in CI (#28). This is a good opportunity to restructure a bit for the future. Many of these linting errors came from the template used to generate the packages.

**Comment by openjck** [comment]
I'm still getting some errors from Svelte files when running `npm run lint`. They don't show up when running `npx eslint .` because ESLint isn't configured to check Svelte files by default.

Most (but not all) are related to the following bug. I'd be more than happy to resolve the issues that remain.

https://github.com/sveltejs/eslint-plugin-svelte3/issues/41
