### ISSUE TITLE
add storybook-deployer to list of dev dependencies

### ISSUE THREAD

**Issue by hamilton** [graph-paper-org/graph-paper#59]
In hunting down #57, I'm noticing that whoever added the storybook deployer didn't actually put it in `package.json`. This should be fairly straightforward to add.

**Comment by robhudson** [comment]
Yeah, John and I agreed that with the storybook deployer as a github action, nobody would need to manually deploy the storybook. And since that all happens on Github servers and is [installed explicitly as part of the github action](https://github.com/graph-paper-org/graph-paper/blob/main/.github/workflows/storybook-deploy.yml#L23), it wasn't needed in the package.json.
